#config.py

# ----- Main Simulation Controls -----
SIMULATION_TICKS = 24000
SIMULATION_CYCLES = 10
RANDOMIZATION_SEED = 42
REPLICATION_FACTOR = 1
MAX_REPLICATION_FACTOR = 50
NUMBER_OF_CHUNKS = 1000


# ----- Upload Node Controls -----
UPLOAD_WAIT_TIME_MINUTES = (60, 240)


# ----- Host Node Controls -----
UPTIME_RANGE_MINUTES = (180, 1440)
DOWNTIME_RANGE_MINUTES = (30, 360)


# ----- Download Node Controls -----
DOWNLOAD_WAIT_TIME_MINUTES = (2, 30)

# ----- Network Speed Controls -----
HOST_UPLOAD_SPEED_MBPS = 5
USER_DOWNLOAD_BANDWIDTH_MBPS = 100
CHUNK_SIZE_MB = 10
